---
# Example Playbook for SWM Backup New Role
# This playbook demonstrates how to use the role with different configurations

- name: SWM Backup New Role - Complete Example
  hosts: local
  gather_facts: true  # Required for remote host CSV file copying
  vars:
    # ALPACA API Configuration
    ALPACA_Operator_API_Protocol: "https"
    ALPACA_Operator_API_Port: 8443
    ALPACA_Operator_API_Username: "pms*"
    ALPACA_Operator_API_Password: "pms"  # Use vault in production: "{{ vault_alpaca_password }}"
    ALPACA_Operator_API_Validate_Certs: false

  tasks:
    # Basic usage with default SLA definitions
    - name: Execute SWM Backup New Role with default settings
      include_role:
        name: swm_backup_new
      # Uncomment and modify the vars section below for advanced usage
      # vars:
      #   # Custom SLA definitions example
      #   sla_definitions:
      #     "SLA1":
      #       name: "Critical Production"
      #       description: "Mission-critical production systems"
      #       command_defaults:
      #         processId: 901
      #         parameters: "-p critical -t __SYSTEM_TYPE__ -s __HDB_NW_SID__ -az __SYSTEM_AZ__ --priority high"
      #         parametersNeeded: false
      #         disabled: false
      #         critical: true
      #         autoDeploy: true
      #         schedule:
      #           period: "every_5min"
      #           time: "00:00:00"
      #           cronExpression: ""
      #           daysOfWeek: ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"]
      #         history:
      #           documentAllRuns: true
      #           retention: 604800  # 7 days
      #         timeout:
      #           type: "custom"
      #           value: 120
      #         escalation:
      #           mailEnabled: true
      #           smsEnabled: true
      #           mailAddress: "critical-alerts@company.com"
      #           smsAddress: "+1234567890"
      #           minFailureCount: 1
      #           triggers:
      #             everyChange: true
      #             toRed: true
      #             toYellow: false
      #             toGreen: false
      #     "SLA2":
      #       name: "Standard Production"
      #       description: "Standard production systems"
      #       command_defaults:
      #         processId: 802
      #         parameters: "-p production -t __SYSTEM_TYPE__ -s __HDB_NW_SID__ -az __SYSTEM_AZ__"
      #         parametersNeeded: false
      #         disabled: false
      #         critical: true
      #         autoDeploy: true
      #         schedule:
      #           period: "hourly"
      #           time: "00:00:00"
      #           cronExpression: ""
      #           daysOfWeek: ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"]
      #         history:
      #           documentAllRuns: true
      #           retention: 1209600  # 14 days
      #         timeout:
      #           type: "default"
      #           value: 300
      #         escalation:
      #           mailEnabled: true
      #           smsEnabled: false
      #           mailAddress: "prod-monitoring@company.com"
      #           smsAddress: ""
      #           minFailureCount: 2
      #           triggers:
      #             everyChange: false
      #             toRed: true
      #             toYellow: false
      #             toGreen: false
      #     "SLA3":
      #       name: "Development Environment"
      #       description: "Development and testing systems"
      #       command_defaults:
      #         processId: 703
      #         parameters: "-p development -t __SYSTEM_TYPE__ -s __HDB_NW_SID__ -az __SYSTEM_AZ__ --env dev"
      #         parametersNeeded: false
      #         disabled: false
      #         critical: false
      #         autoDeploy: true
      #         schedule:
      #           period: "daily"
      #           time: "02:00:00"
      #           cronExpression: ""
      #           daysOfWeek: ["monday", "tuesday", "wednesday", "thursday", "friday"]
      #         history:
      #           documentAllRuns: true
      #           retention: 259200  # 3 days
      #         timeout:
      #           type: "default"
      #           value: 600
      #         escalation:
      #           mailEnabled: true
      #           smsEnabled: false
      #           mailAddress: "dev-team@company.com"
      #           smsAddress: ""
      #           minFailureCount: 3
      #           triggers:
      #             everyChange: false
      #             toRed: true
      #             toYellow: false
      #             toGreen: false
      #     "SLA4":
      #       name: "Backup Environment"
      #       description: "Backup and archive systems"
      #       command_defaults:
      #         processId: 604
      #         parameters: "-p backup -t __SYSTEM_TYPE__ -s __HDB_NW_SID__ -az __SYSTEM_AZ__ --backup-mode"
      #         parametersNeeded: false
      #         disabled: false
      #         critical: false
      #         autoDeploy: true
      #         schedule:
      #           period: "daily"
      #           time: "03:00:00"
      #           cronExpression: ""
      #           daysOfWeek: ["monday", "tuesday", "wednesday", "thursday", "friday"]
      #         history:
      #           documentAllRuns: true
      #           retention: 259200  # 3 days
      #         timeout:
      #           type: "default"
      #           value: 900
      #         escalation:
      #           mailEnabled: true
      #           smsEnabled: false
      #           mailAddress: "backup-team@company.com"
      #           smsAddress: ""
      #           minFailureCount: 5
      #           triggers:
      #             everyChange: false
      #             toRed: true
      #             toYellow: false
      #             toGreen: false
      #
      #   # Processing options example
      #   processing_options:
      #     create_commands: true      # Set to false for validation-only mode
      #     validate_data: true
      #     log_level: "debug"

    - name: Display completion message
      ansible.builtin.debug:
        msg: |
          SWM Backup New Role execution completed successfully!

          Summary:
          - CSV file processed: {{ csv_source_file | default('N/A') }}
          - Total systems: {{ csv_data | length if csv_data is defined else 0 }}
          - Commands created: {{ commands_created | default(0) }}

          SLA Distribution:
          - SLA1 systems: {{ csv_data | selectattr('system_sla', 'equalto', 'SLA1') | list | length if csv_data is defined else 0 }}
          - SLA2 systems: {{ csv_data | selectattr('system_sla', 'equalto', 'SLA2') | list | length if csv_data is defined else 0 }}
          - SLA3 systems: {{ csv_data | selectattr('system_sla', 'equalto', 'SLA3') | list | length if csv_data is defined else 0 }}
          - SLA4 systems: {{ csv_data | selectattr('system_sla', 'equalto', 'SLA4') | list | length if csv_data is defined else 0 }}

          Note: To use custom SLA definitions, uncomment and modify the 'vars' section in the role task above.