---
# SWM Backup Template Role Defaults

# CSV File Configuration
csv_processor:
  # Input CSV file path
  input_file: "{{ role_path }}/files/swm_prod.csv"

  # CSV delimiter
  delimiter: ";"

  # CSV encoding
  encoding: "utf-8"

  # Whether to skip header row
  skip_header: true

# CSV Column Mapping
csv_columns:
  primary_system: 0
  hdb_nw_sid: 1
  hdb_tenant: 2
  system_type: 3
  system_staging: 4
  system_sla: 5
  system_vm_type: 6
  system_vm_flavor: 7
  system_vdns: 8
  system_az: 9
  hdb_data_min: 10
  hdb_data_max: 11
  hdb_log_min: 12
  hdb_log_max: 13
  hdb_shared_min: 14
  hdb_shared_max: 15
  Instance_no: 16

# Output Configuration
output_config:
  # Output directory for generated files
  output_dir: "{{ playbook_dir }}/generated"
  
  # File naming patterns
  command_file_pattern: "command_{{ item.system_name | replace(' ', '_') | lower }}.yml"
  consolidated_file: "consolidated_commands.yml"
  inventory_file: "inventory.ini"
  variables_file: "variables.yml"
  readme_file: "README.md"

# Template Configuration
template_config:
  # Template directory
  template_dir: "{{ role_path }}/templates"
  
  # Template files
  command_template: "command_template.yml.j2"
  consolidated_template: "consolidated_template.yml.j2"
  inventory_template: "inventory_template.ini.j2"
  variables_template: "variables_template.yml.j2"
  readme_template: "README_template.md.j2"

# Processing Options
processing_options:
  # Whether to generate individual command files
  generate_individual_files: true
  
  # Whether to generate consolidated file
  generate_consolidated_file: true
  
  # Whether to generate inventory file
  generate_inventory: true
  
  # Whether to generate variables file
  generate_variables: true
  
  # Whether to generate README
  generate_readme: true
  
  # Whether to validate CSV data before processing
  validate_data: true
  
  # Log level for processing
  log_level: "info"

# ALPACA API Configuration (will be built dynamically in tasks)
# Required variables that must be set by the user:
# - ALPACA_Operator_API_Protocol (optional, defaults to 'https')
# - ALPACA_Operator_API_Port (optional, defaults to 8443)
# - ALPACA_Operator_API_Username (required)
# - ALPACA_Operator_API_Password (required)
# - ALPACA_Operator_API_Validate_Certs (optional, defaults to false) 