---
dependencies: []
galaxy_info:
  role_name: hana_backup
  author: ALPACA Operator Team
  description: Generate and execute ALPACA Operator commands based on CSV data and SLA levels
  company: ""
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: EL
      versions:
        - "7"
        - "8"
        - "9"
  galaxy_tags:
    - alpaca
    - backup
    - hana
    - automation