- name: Configure ALPACA Operator commands                          # Name of the Playbook
  hosts: local                                                      # hostname or group defined in the corresponding inventory
  gather_facts: false

  tasks:
    - name: Ensure a specific command is configured
      pcg.alpaca_operator.alpaca_command:
        # --- System identification (either systemName or systemId is required) ---
        system:
          # systemName: "My System"                                 # Optional if systemId is used
          # systemId: 1                                             # Optional if systemName is used

        command:
          name: "BKP: DB log sync"                                  # Required: command description (acts as identifier in combination with the agentName or agentId)

          # --- Desired state ---
          state: present                                            # present | absent

          # --- Agent assignment (either agentName or agentId is required) ---
          # agentName: "ansible_testing_agent_03"                   # Optional if agentId is used
          # agentId: 123                                            # Optional if agentName is used

          # --- Process configuration ---
          # processId: 801                                          # Optional if processCentralId is used
          # processCentralId: 8990048                               # Optional if processId is used

          # --- Command parameters definition ---
          parameters: "-p GLTarch -s <BKP_LOG_SRC> -l 4 -d <BKP_LOG_DEST1> -r <BKP_LOG_DEST2> -b <BKP_LOG_CLEANUP_INT> -t <BKP_LOG_CLEANUP_INT2> -h DB_HOST"

          # --- Scheduling configuration ---
          schedule:
            period: manually                                        # Options: manually, cron_expression, every_5min, fixed_time, etc.
            time: "12:12:12"                                        # Required for fixed_time or fixed_time_once
            cronExpression: ""                                      # Required if period is 'cron_expression'
            daysOfWeek:                                             # Optional: days when the command should run
              - monday
              - sunday
              - wednesday

          # --- Command flags ---
          parametersNeeded: false
          disabled: true                                            # Set to true to disable the command
          critical: true                                            # Indicates if command is critical
          autoDeploy: false

          # --- Command history retention ---
          history:
            documentAllRuns: false                                  # Whether to log all executions
            retention: 200

          # --- Timeout configuration ---
          timeout:
            type: default                                           # none | default | custom
            value: 30                                               # Timeout in seconds (used if type is custom or default)

          # --- Escalation configuration ---
          escalation:
            mailEnabled: true
            smsEnabled: true
            mailAddress: "monitoring@pcg.io"
            smsAddress: "0123456789"
            minFailureCount: 1
            triggers:
              everyChange: true
              toRed: false
              toYellow: false
              toGreen: true

        # --- API connection configuration ---
        apiConnection:
          host: "{{ inventory_hostname }}"                          # Defined in the corresponding inventory
          protocol: "{{ ALPACA_Operator_API_Protocol }}"            # Defined in the corresponding inventory
          port: "{{ ALPACA_Operator_API_Port }}"                    # Defined in the corresponding inventory
          username: "{{ ALPACA_Operator_API_Username }}"            # Defined in the corresponding inventory
          password: "{{ ALPACA_Operator_API_Password }}"            # Defined in the corresponding inventory
          tls_verify: "{{ ALPACA_Operator_API_Validate_Certs }}"    # Defined in the corresponding inventory