- name: Configure ALPACA Operator commands                          # Name of the Playbook
  hosts: local                                                      # hostname or group defined in the corresponding inventory
  gather_facts: false

  tasks:
    - name: Ensure ALPACA system is present and properly configured
      pcg.alpaca_operator.alpaca_system:
        name: "system01"                                            # Required: existing system name or new system name
        # new_name: "renamed-system01"                              # Optional: rename the system if it exists

        # --- Desired state ---
        state: present                                              # present | absent

        description: "My Test System"                               # Optional description
        magicNumber: 42                                             # Optional: integer between 0 and 59
        checksDisabled: false                                       # Optional: disables automated system checks

        # --- Group assignment (only one required) ---
        # groupName: "test-group"                                   # Optional group assignment by name
        # groupId: 17                                               # Optional group assignment by ID

        # --- RFC connection configuration (optional) ---
        rfcConnection:
          type: instance                                            # none | instance | messageServer
          host: "sap-target-host"
          instanceNumber: 30
          sid: "ABC"                                                # SAP system ID (3 uppercase letters)
          logonGroup: "my-logon-group"                              # Optional for messageServer
          username: "rfc_user"
          password: "rfc_password"
          client: "100"
          sapRouterString: "/H/1.2.3.4/S/3299/H/5.6.7.8/"
          sncEnabled: false

        # --- Agent assignment ---
        # Hint: Any agent referenced in a command for this system MUST be declared here as well.
        #       Otherwise, Ansible may attempt to remove unlisted agents and fail during execution.
        agents:
          - name: "localhost"
          - name: "agent-01"

        # --- Variable definitions ---
        variables:
          - name: "<BKP_DATA_DEST2>"
            value: "11"
          - name: "<BKP_DATA_CLEANUP_INT>"
            value: "19"
          - name: "<BKP_DATA_CLEANUP_INT2>"
            value: "this is a string"

        # --- API connection configuration ---
        apiConnection:
          host: "{{ ALPACA_Operator_API_Host }}"                          # Defined in the corresponding inventory
          protocol: "{{ ALPACA_Operator_API_Protocol }}"            # Defined in the corresponding inventory
          port: "{{ ALPACA_Operator_API_Port }}"                    # Defined in the corresponding inventory
          username: "{{ ALPACA_Operator_API_Username }}"            # Defined in the corresponding inventory
          password: "{{ ALPACA_Operator_API_Password }}"            # Defined in the corresponding inventory
          tls_verify: "{{ ALPACA_Operator_API_Validate_Certs }}"    # Defined in the corresponding inventory