- name: Manage ALPACA Operator group                                # Name of the Playbook
  hosts: local                                                      # Hostname or group defined in the corresponding inventory
  gather_facts: false

  tasks:
    - name: Ensure ALPACA group is present
      pcg.alpaca_operator.alpaca_group:
        name: "testgroup01"                                         # Required: existing or new group name
        # new_name: "renamed-group"                                 # Optional: rename the group if it exists

        # --- Desired state ---
        state: present                                              # present | absent

        # --- API connection configuration ---
        apiConnection:
          host: "{{ ALPACA_Operator_API_Host }}"                          # Defined in the corresponding inventory
          protocol: "{{ ALPACA_Operator_API_Protocol }}"            # Defined in the corresponding inventory
          port: "{{ ALPACA_Operator_API_Port }}"                    # Defined in the corresponding inventory
          username: "{{ ALPACA_Operator_API_Username }}"            # Defined in the corresponding inventory
          password: "{{ ALPACA_Operator_API_Password }}"            # Defined in the corresponding inventory
          tls_verify: "{{ ALPACA_Operator_API_Validate_Certs }}"    # Defined in the corresponding inventory