---
- name: HANA Backup - Generate and Execute Commands from CSV
  hosts: local
  gather_facts: false

  vars:
    csv_file: "../systems.csv"

  tasks:
    - name: Include hana_backup role
      include_role:
        name: pcg.alpaca_operator.hana_backup