---
# CSV file path
csv_file: "/tmp/swm_prod.csv"

role_defaults:
  command_defaults:
    # Global command defaults (only applied if not set at SLA or command level)
    state: present
    schedule:
      period: fixed_time
      time: "12:12:12"
      # cronExpression: ""
      daysOfWeek:
        - monday
        - tuesday
        - wednesday
        - thursday
        - friday
        - saturday
        - sunday
    parametersNeeded: true
    disabled: false
    critical: false
    history:
      documentAllRuns: true
      retention: 200
    autoDeploy: false
    timeout:
      type: custom
      value: 4000
    escalation:
      mailEnabled: true
      smsEnabled: true
      mailAddress: "monitoring@pcg.io"
      smsAddress: "0123456789"
      minFailureCount: 1
      triggers:
        everyChange: true
        toRed: true
        toYellow: true
        toGreen: true
  commands:
    # A default command set for a service level
    - name: "HANA BACKUP LOG"
      processCentralId: 12345678
      parameters: "-s <HANA_DB_SID> -n 4 -e blob -o <BKP_LB_LOG_01> -z $SKEY -r { blob_log_ret } -k { local_log_ret } -y -"
      schedule:
        period: fixed_time
        time: "12:12:12"
        # cronExpression: ""
        daysOfWeek:
          - monday
          - tuesday
          - wednesday
          - thursday
          - friday
          - saturday
          - sunday
  service_levels:
    SLA1:
      variables:
        local_file_ret: "<CZ_LOCAL_FILE_RET_CLASS_1>"
        local_snap_ret: "<CZ_LOCAL_SNAP_RET_CLASS_1>"
        local_log_ret: "<CZ_LOCAL_LOG_RET_CLASS_1>"
        blob_log_ret: "<CZ_BLOB_LOG_RET_CLASS_1>"
        blob_file_ret: "<CZ_BLOB_FILE_RET_CLASS_1>"
        blob_file_ret_monthly: "<CZ_BLOB_FILE_RET_MONTHLY_CLASS_1>"
        blob_file_ret_yearly: "<CZ_BLOB_FILE_RET_YEARLY_CLASS_1>"
      command_defaults:
        # SLA level command defaults (only applied if not set at command level)
        critical: true
      commands:
        - name: "HANA BACKUP LOG"
          schedule:
            period: fixed_time
            time: "13:13:13"
            # cronExpression: ""
            daysOfWeek:
              - monday
              - tuesday
              - wednesday
              - thursday
              - friday
              - saturday
              - sunday
    SLA2:
      variables:
        blob_log_ret: "<CZ_BLOB_LOG_RET_CLASS_2>"
      command_defaults:
        # SLA level command defaults (only applied if not set at command level)
        critical: false
      commands: