---
# CSV file path
csv_file: "/tmp/swm_prod.csv"

role_defaults:
  global:
    # defaults:
    #   state: present
    # commands:
    #   - name: "BKP: HANA log multi incl. external"
    #     processCentralId: 8990048
    #     parameters: "-s <HANA_DB_SID> -n 4 -e blob -o <BKP_LB_LOG_01> -z $SKEY -r <CZ_BLOB_LOG_RET_CLASS_1> -k <CZ_LOCAL_LOG_RET_CLASS_1> -y -"
    #     schedule:
    #       period: fixed_time
    #       time: "12:12:12"
    #       # cronExpression: ""
    #       daysOfWeek:
    #         - monday
    #         - tuesday
    #         - wednesday
    #         - thursday
    #         - friday
    #         - saturday
    #         - sunday

  global_defaults:
    state: present
    parametersNeeded: true
    disabled: false
    critical: true
    history:
      documentAllRuns: true
      retention: 200
    autoDeploy: false
    timeout:
      type: custom
      value: 4000
    escalation:
      mailEnabled: true
      smsEnabled: true
      mailAddress: "monitoring@pcg.io"
      smsAddress: "0123456789"
      minFailureCount: 1
      triggers:
        everyChange: true
        toRed: true
        toYellow: true
        toGreen: true
  service_levels:
    SLA1:
      # defaults:
      #   critical: false
      commands:
        - name: "BKP: HANA log multi incl. external"
          processCentralId: 8990048
          parameters: "-s <HANA_DB_SID> -n 4 -e blob -o <BKP_LB_LOG_01> -z $SKEY -r <CZ_BLOB_LOG_RET_CLASS_1> -k <CZ_LOCAL_LOG_RET_CLASS_1> -y -"
          schedule:
            period: fixed_time
            time: "12:12:12"
            # cronExpression: ""
            daysOfWeek:
              - monday
              - tuesday
              - wednesday
              - thursday
              - friday
              - saturday
              - sunday
