---
# CSV file path
csv_file: "/tmp/swm_prod.csv"

role_defaults:
  # command_defaults:
  #   state: present
  #   disabled: false
  # commands:
  # # The default command set for a service level
  #   - name: "HANA BACKUP LOG"
  #     processCentralId: 8990048
  #     parameters: "-s <HANA_DB_SID> -n 4 -e blob -o <BKP_LB_LOG_01> -z $SKEY -r <CZ_BLOB_LOG_RET_CLASS_1> -k <CZ_LOCAL_LOG_RET_CLASS_1> -y -"
  #   - name: "HANA RESTORE FILE"
  #     processCentralId: 1234567
  #     parameters: "-s <HANA_DB_SID> -n 4 -e blob -o <BKP_LB_LOG_01> -z $SKEY -r <CZ_BLOB_LOG_RET_CLASS_1> -k <CZ_LOCAL_LOG_RET_CLASS_1> -y -"
  # service_levels_:
  #   SLA1:
  #     variables:
  #       blob_log_ret: "<CZ_BLOB_LOG_RET_CLASS_1>"
  #     command_defaults:
  #       critical: true
  #     commands:
  #       # Include role_defaults.commands
  #       - name: "Some additional command"
  #       - name: "Or Override something"
  #   SLA2:
  #     variables:
  #       blob_log_ret: "<CZ_BLOB_LOG_RET_CLASS_2>"
  #     command_defaults:
  #       critical: false
  #     commands:
  #       # Include role_defaults.commands
  #       - name: "Some additional command"
  #       - name: "Or Override something"


  global_defaults:
    state: present
    parametersNeeded: true
    disabled: false
    critical: true
    history:
      documentAllRuns: true
      retention: 200
    autoDeploy: false
    timeout:
      type: custom
      value: 4000
    escalation:
      mailEnabled: true
      smsEnabled: true
      mailAddress: "monitoring@pcg.io"
      smsAddress: "0123456789"
      minFailureCount: 1
      triggers:
        everyChange: true
        toRed: true
        toYellow: true
        toGreen: true
  service_levels:
    SLA1:
      # defaults:
      #   critical: false
      commands:
        - name: "HANA BACKUP LOG"
          processCentralId: 8990048
          parameters: "-s <HANA_DB_SID> -n 4 -e blob -o <BKP_LB_LOG_01> -z $SKEY -r <CZ_BLOB_LOG_RET_CLASS_1> -k <CZ_LOCAL_LOG_RET_CLASS_1> -y -"
          schedule:
            period: fixed_time
            time: "12:12:12"
            # cronExpression: ""
            daysOfWeek:
              - monday
              - tuesday
              - wednesday
              - thursday
              - friday
              - saturday
              - sunday
        - name: "HANA RESTORE FILE"
          processCentralId: 8990048
          parameters: "-q <HANA_DB_SID> -w <HANA_VHOST> -e <HANA_DB_SID> -j 1 -t AUTO -k 2021-06-16.10:00:00 -l <BKP_DATA_DEST1>/restore -g SYSTEMDB,<HANA_DB_SID>!<HANA_DB_SID> -A xxxx -Q 1 -T 0 -J BACKUP -W <HANA_VHOST> -X ${SID} -E 2 -B <BKP_LB_DATA_01> -P $SKEY -U -"
          schedule:
            period: fixed_time
            time: "12:12:12"
            # cronExpression: ""
            daysOfWeek:
              - monday
              - tuesday
              - wednesday
              - thursday
              - friday
              - saturday
              - sunday
        - name: "HANA RESTORE SNAP"
          processCentralId: 8990048
          parameters: "-q <HANA_DB_SID> -w <HANA_VHOST> -e <HANA_DB_SID> -j 0 -t AUTO -k 2021-06-16.10:00:00 -l <BKP_DATA_DEST1>/restore -g SYSTEMDB,<HANA_DB_SID>!<HANA_DB_SID> -A xxxx -Q 1 -T 0 -J BACKUP -W <HANA_VHOST> -X ${SID} -E 2 -B <BKP_LB_DATA_01> -P $SKEY"
          schedule:
            period: fixed_time
            time: "12:12:12"
            # cronExpression: ""
            daysOfWeek:
              - monday
              - tuesday
              - wednesday
              - thursday
              - friday
              - saturday
              - sunday
        - name: "HANA BACKUP SNAP"
          processCentralId: 8990048
          parameters: "-s __csv.systemName__ -i <HANA_SYS_NR> -m pms_onl_cons -c localhost -t 3 -p <CZ_LOCAL_SNAP_RET_CLASS_1> -u BACKUP"
          schedule:
            period: fixed_time
            time: "12:12:12"
            # cronExpression: ""
            daysOfWeek:
              - monday
              - tuesday
              - wednesday
              - thursday
              - friday
              - saturday
              - sunday
        - name: "HANA BACKUP FILE DAILY"
          processCentralId: 8990048
          parameters: "-s __csv.systemName__ -d <BKP_DATA_DEST1> -r - -b $LOCAL_FILE_RET -t ALL -m file -p full -u BACKUP -A blob -B <BKP_LB_DATA_01> -C $SKEY -D $BLOB_FILE_RET"
          schedule:
            period: cron_expression
            cronExpression: "0 0 21 2-31 * ? *"
          timeout:
            type: custom
            value: 40000
        - name: "HANA BACKUP FILE MONTHLY"
          processCentralId: 8990048
          parameters: "-s __csv.systemName__ -d <BKP_DATA_DEST1_MONTHLY> -r - -b $LOCAL_FILE_RET -t ALL -m file -p full -u BACKUP -A blob -B <BKP_LB_DATA_01> -C $SKEY -D $CZ_BLOB_FILE_RET_MONTHLY_CLASS_1"
          schedule:
            period: cron_expression
            cronExpression: "0 0 21 1 * ? *"
          timeout:
            type: custom
            value: 40000
        - name: "HANA BACKUP FILE YEARLY"
          processCentralId: 8990048
          parameters: "-s __csv.systemName__ -d <BKP_DATA_DEST1_YEARLY> -r - -b $LOCAL_FILE_RET -t ALL -m file -p full -u BACKUP -A blob -B <BKP_LB_DATA_01> -C $SKEY -D $BLOB_FILE_RET_YEARLY"
          schedule:
            period: fixed_time
            time: "12:12:12"
            # cronExpression: ""
            daysOfWeek:
              - monday
              - tuesday
              - wednesday
              - thursday
              - friday
              - saturday
              - sunday
            timeout:
              type: custom
              value: 40000
        - name: "FS BACKUP INCR"
          processCentralId: 8990048
          parameters: "-a __csv.systemName__ -b <BKP_LB_FS_01> -c 1 -d $FSBKPBASE -e /backup -f localhost -g $SKEY -h <CZ_LOCAL_FILE_RET_CLASS_3> -i <CZ_BLOB_FILE_RET_CLASS_3>"
          schedule:
            period: cron_expression
            cronExpression: "0 0 22 ? * MON,TUE,WED,THU,FRI,SAT *"
            timeout:
              type: custom
              value: 4000
        - name: "FS BACKUP FULL"
          processCentralId: 8990048
          parameters: "-a $SID -b <BKP_LB_FS_01> -c 0 -d $FSBKPBASE -e /backup -f localhost -g $SKEY -h <CZ_LOCAL_FILE_RET_CLASS_3> -i <CZ_BLOB_FILE_RET_CLASS_3>"
          schedule:
            period: cron_expression
            cronExpression: "0 0 22 ? * SUN *"
            timeout:
              type: custom
              value: 40000
