---
# Example Playbook for SWM Backup Template Role
# This playbook generates files that can be executed to achieve the same result as swm_backup role

- name: Generate ALPACA Commands from CSV using Template Role
  hosts: local
  gather_facts: true
  vars:
    # ALPACA API Configuration
    ALPACA_Operator_API_Protocol: "https"
    ALPACA_Operator_API_Port: 8443
    ALPACA_Operator_API_Username: "pms*"
    ALPACA_Operator_API_Password: "pms"
    ALPACA_Operator_API_Validate_Certs: false

    # SLA Definitions (same as in swm_backup role)
    sla_definitions:
      "SLA1":
        name: "Production"
        description: "Production systems"
        command_defaults:
          processId: 801
          parameters: "-p prod -t __SYSTEM_TYPE__ -s __HDB_NW_SID__ -az __SYSTEM_AZ__"
          parametersNeeded: false
          disabled: false
          critical: true
          autoDeploy: true
          schedule:
            period: "daily"
            time: "02:00:00"
            cronExpression: ""
            daysOfWeek: ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"]
          history:
            documentAllRuns: true
            retention: 604800  # 7 days
          timeout:
            type: "default"
            value: 300
          escalation:
            mailEnabled: true
            smsEnabled: false
            mailAddress: "prod-monitoring@company.com"
            smsAddress: ""
            minFailureCount: 2
            triggers:
              everyChange: false
              toRed: true
              toYellow: false
              toGreen: false
      "SLA2":
        name: "Staging"
        description: "Staging systems"
        command_defaults:
          processId: 802
          parameters: "-p staging -t __SYSTEM_TYPE__ -s __HDB_NW_SID__ -az __SYSTEM_AZ__"
          parametersNeeded: false
          disabled: false
          critical: false
          autoDeploy: true
          schedule:
            period: "daily"
            time: "03:00:00"
            cronExpression: ""
            daysOfWeek: ["monday", "tuesday", "wednesday", "thursday", "friday"]
          history:
            documentAllRuns: true
            retention: 259200  # 3 days
          timeout:
            type: "default"
            value: 600
          escalation:
            mailEnabled: true
            smsEnabled: false
            mailAddress: "staging-team@company.com"
            smsAddress: ""
            minFailureCount: 3
            triggers:
              everyChange: false
              toRed: true
              toYellow: false
              toGreen: false
      "SLA3":
        name: "Development"
        description: "Development systems"
        command_defaults:
          processId: 803
          parameters: "-p dev -t __SYSTEM_TYPE__ -s __HDB_NW_SID__ -az __SYSTEM_AZ__"
          parametersNeeded: false
          disabled: false
          critical: false
          autoDeploy: true
          schedule:
            period: "daily"
            time: "04:00:00"
            cronExpression: ""
            daysOfWeek: ["monday", "tuesday", "wednesday", "thursday", "friday"]
          history:
            documentAllRuns: true
            retention: 172800  # 2 days
          timeout:
            type: "default"
            value: 900
          escalation:
            mailEnabled: true
            smsEnabled: false
            mailAddress: "dev-team@company.com"
            smsAddress: ""
            minFailureCount: 5
            triggers:
              everyChange: false
              toRed: true
              toYellow: false
              toGreen: false
      "SLA4":
        name: "Backup"
        description: "Backup systems"
        command_defaults:
          processId: 804
          parameters: "-p backup -t __SYSTEM_TYPE__ -s __HDB_NW_SID__ -az __SYSTEM_AZ__"
          parametersNeeded: false
          disabled: false
          critical: false
          autoDeploy: true
          schedule:
            period: "daily"
            time: "05:00:00"
            cronExpression: ""
            daysOfWeek: ["monday", "tuesday", "wednesday", "thursday", "friday"]
          history:
            documentAllRuns: true
            retention: 259200  # 3 days
          timeout:
            type: "default"
            value: 1200
          escalation:
            mailEnabled: true
            smsEnabled: false
            mailAddress: "backup-team@company.com"
            smsAddress: ""
            minFailureCount: 5
            triggers:
              everyChange: false
              toRed: true
              toYellow: false
              toGreen: false

  tasks:
    - name: Execute SWM Backup Template Role
      include_role:
        name: swm_backup_template
      vars:
        # Optional: Customize output configuration
        output_config:
          output_dir: "{{ playbook_dir }}/generated_commands"
          command_file_pattern: "command_{{ item.system_name | replace(' ', '_') | lower }}.yml"
          consolidated_file: "all_commands.yml"
          inventory_file: "alpaca_inventory.ini"
          variables_file: "system_variables.yml"
          readme_file: "GENERATED_README.md"

        # Optional: Customize processing options
        processing_options:
          generate_individual_files: true
          generate_consolidated_file: true
          generate_inventory: true
          generate_variables: true
          generate_readme: true
          validate_data: true
          log_level: "info"

    - name: Display generation summary
      ansible.builtin.debug:
        msg:
          - "SWM Backup Template Role execution completed!"
          - ""
          - "Generated files in: {{ output_config.output_dir | default('generated') }}"
          - "- Individual command files: {{ processing_options.generate_individual_files | default(true) }}"
          - "- Consolidated playbook: {{ processing_options.generate_consolidated_file | default(true) }}"
          - "- Inventory file: {{ processing_options.generate_inventory | default(true) }}"
          - "- Variables file: {{ processing_options.generate_variables | default(true) }}"
          - "- README file: {{ processing_options.generate_readme | default(true) }}"
          - ""
          - "Next steps:"
          - "1. Review generated files in the output directory"
          - "2. Execute the consolidated playbook:"
          - "   ansible-playbook -i generated/alpaca_inventory.ini generated/all_commands.yml"
          - "3. Or execute individual command files as needed"