---
# Generate Individual Command Files

- name: Initialize individual files counter
  ansible.builtin.set_fact:
    individual_files_generated: 0

- name: Generate individual command files for each CSV row
  ansible.builtin.template:
    src: "{{ template_config.command_template }}"
    dest: "{{ output_config.output_dir }}/{{ output_config.command_file_pattern | replace('{{ item.system_name | replace(\" \", \"_\") | lower }}', item.system_name | replace(' ', '_') | lower) }}"
    mode: '0644'
  vars:
    csv_row: "{{ item }}"
    sla_config: "{{ sla_definitions[item.system_sla] }}"
    command_name: "{{ sla_config.name }} Backup Command - {{ item.system_name }}"
    alpaca_api: "{{ alpaca_api }}"
  loop: "{{ csv_data }}"
  loop_control:
    loop_var: item
    label: "{{ item.system_name }} ({{ item.system_sla }})"
  register: individual_command_results

- name: Count successfully generated individual files
  ansible.builtin.set_fact:
    individual_files_generated: "{{ individual_files_generated | int + (1 if item.changed else 0) }}"
  loop: "{{ individual_command_results.results }}"
  loop_control:
    label: "{{ item.item.system_name if item.item is defined else 'Unknown' }}"

- name: Display individual file generation summary
  ansible.builtin.debug:
    msg: |
      Individual Command File Generation Summary:
      - Total systems processed: {{ csv_data | length }}
      - Files generated: {{ individual_files_generated }}
      - Files already existing: {{ csv_data | length | int - individual_files_generated | int }}
      - Output directory: {{ output_config.output_dir }}

- name: Display failed individual file generations
  ansible.builtin.debug:
    msg: |
      Failed to generate command file for system: {{ item.item.system_name }}
      Error: {{ item.msg | default('Unknown error') }}
  loop: "{{ individual_command_results.results }}"
  loop_control:
    label: "{{ item.item.system_name if item.item is defined else 'Unknown' }}"
  when: item.failed | default(false)

- name: Fail if any individual file generation failed
  ansible.builtin.fail:
    msg: "One or more individual command file generations failed. Check the debug output above for details."
  when: individual_command_results.results | selectattr('failed', 'defined') | selectattr('failed', 'equalto', true) | list | length > 0 