---
# Generate Consolidated Command File

- name: Generate consolidated command file
  ansible.builtin.template:
    src: "{{ template_config.consolidated_template }}"
    dest: "{{ output_config.output_dir }}/{{ output_config.consolidated_file }}"
    mode: '0644'
  vars:
    csv_data: "{{ csv_data }}"
    sla_definitions: "{{ sla_definitions }}"
    alpaca_api: "{{ alpaca_api }}"
  register: consolidated_file_result

- name: Set consolidated file generation status
  ansible.builtin.set_fact:
    consolidated_file_generated: "{{ consolidated_file_result.changed | default(false) }}"

- name: Display consolidated file generation result
  ansible.builtin.debug:
    msg: |
      Consolidated Command File Generation:
      - File: {{ output_config.output_dir }}/{{ output_config.consolidated_file }}
      - Status: {{ 'Generated' if consolidated_file_generated else 'Already exists' }}
      - Total commands included: {{ csv_data | length }}

- name: Fail if consolidated file generation failed
  ansible.builtin.fail:
    msg: "Failed to generate consolidated command file. Error: {{ consolidated_file_result.msg | default('Unknown error') }}"
  when: consolidated_file_result.failed | default(false) 