---
galaxy_info:
  author: Jan-Karsten Hansmeyer (@pcg)
  description: CSV Processor Role for ALPACA Operator with SLA definitions
  company: Public Cloud Group
  license: GPL-3.0-or-later
  min_ansible_version: "2.12"
  platforms:
    - name: EL
      versions:
        - "7"
        - "8"
        - "9"
    - name: Ubuntu
      versions:
        - "all"
  galaxy_tags:
    - csv
    - alpaca
    - automation

dependencies: []