---
# Create ALPACA Commands

- name: Initialize command creation counter
  ansible.builtin.set_fact:
    commands_created: 0

- name: Create ALPACA commands for each CSV row
  include_tasks: create_commands_for_row.yml
  loop: "{{ csv_data }}"
  loop_control:
    loop_var: csv_row
    label: "{{ csv_row.system_name }} ({{ csv_row.system_sla }})"

- name: Display command creation summary
  ansible.builtin.debug:
    msg: |
      Command Creation Summary:
      - Total systems processed: {{ csv_data | length }}
      - Commands created/updated: {{ commands_created }}
      - Commands already existing: {{ (csv_data | length * 3) - commands_created | int }}

      SLA Breakdown:
      - SLA1 ({{ sla_definitions.SLA1.name }}): {{ csv_data | selectattr('system_sla', 'equalto', 'SLA1') | list | length }} systems
      - SLA2 ({{ sla_definitions.SLA2.name }}): {{ csv_data | selectattr('system_sla', 'equalto', 'SLA2') | list | length }} systems
      - SLA3 ({{ sla_definitions.SLA3.name }}): {{ csv_data | selectattr('system_sla', 'equalto', 'SLA3') | list | length }} systems
      - SLA4 ({{ sla_definitions.SLA4.name }}): {{ csv_data | selectattr('system_sla', 'equalto', 'SLA4') | list | length }} systems