---
# CSV Processor Role - Playbook Generation Tasks

- name: Generate individual command playbooks
  template:
    src: command_playbook.yml.j2
    dest: "{{ csv_processor.output_dir }}/command_{{ item.command.name | regex_replace('[^a-zA-Z0-9]', '_') }}.yml"
    mode: '0644'
  loop: "{{ processed_commands }}"
  loop_control:
    label: "{{ item.command.name }}"

- name: Generate consolidated playbook
  template:
    src: consolidated_playbook.yml.j2
    dest: "{{ csv_processor.output_dir }}/consolidated_commands.yml"
    mode: '0644'

- name: Generate SLA-specific playbooks
  template:
    src: sla_playbook.yml.j2
    dest: "{{ csv_processor.output_dir }}/sla_{{ item }}_commands.yml"
    mode: '0644'
  loop:
    - "SLA1"
    - "SLA2"
    - "SLA3"

- name: Generate system-specific playbooks
  template:
    src: system_playbook.yml.j2
    dest: "{{ csv_processor.output_dir }}/system_{{ item | regex_replace('[^a-zA-Z0-9]', '_') }}_commands.yml"
    mode: '0644'
  loop: "{{ processing_summary.systems }}"

- name: Generate inventory template
  template:
    src: inventory_template.ini.j2
    dest: "{{ csv_processor.output_dir }}/inventory.ini"
    mode: '0644'

- name: Generate variables file
  template:
    src: variables.yml.j2
    dest: "{{ csv_processor.output_dir }}/variables.yml"
    mode: '0644'

- name: Generate README file
  template:
    src: README.md.j2
    dest: "{{ csv_processor.output_dir }}/README.md"
    mode: '0644'

- name: Display generated files
  debug:
    msg: |
      Generated Playbooks:
      - Individual command playbooks: {{ processed_commands | length }} files
      - Consolidated playbook: consolidated_commands.yml
      - SLA-specific playbooks: sla_1_commands.yml, sla_2_commands.yml, sla_3_commands.yml
      - System-specific playbooks: {{ processing_summary.systems | length }} files
      - Inventory template: inventory.ini
      - Variables file: variables.yml
      - Documentation: README.md
      
      Output directory: {{ csv_processor.output_dir }} 