---
galaxy_info:
  author: PCG Team
  description: SWM Backup New - SLA-based ALPACA command creation from CSV data
  company: PCG
  license: GPL-3.0-or-later
  min_ansible_version: "2.11"
  platforms:
    - name: EL
      versions:
        - "8"
        - "9"
    - name: Ubuntu
      versions:
        - focal
        - jammy
    - name: Debian
      versions:
        - buster
        - bullseye
  galaxy_tags:
    - alpaca
    - backup
    - sla
    - csv
    - automation
    - monitoring

dependencies: [] 