---
galaxy_info:
  author: PCG Team
  description: Template-based SWM Backup Role for ALPACA Operator
  company: PCG
  
  # If the issue tracker for your role is not on github, uncomment the
  # next line and provide a value
  # issue_tracker_url: http://example.com/issue/tracker

  # Choose a valid license ID from https://spdx.org/licenses/ (or, for
  # company/proprietary licensed software, use "Proprietary")
  license: MIT

  min_ansible_version: "2.12"

  # If this a Container Enabled role, provide the minimum Ansible Container version.
  # min_ansible_container_version:

  #
  # Provide a list of platforms, and for each platform/version/arch combination,
  # provide the list of Ansible versions in which it has been tested.
  #
  platforms:
    - name: EL
      versions:
        - "7"
        - "8"
        - "9"
    - name: Ubuntu
      versions:
        - bionic
        - focal
        - jammy
    - name: Debian
      versions:
        - buster
        - bullseye
        - bookworm

  #
  # Provide a list of Ansible versions in which this role has been tested.
  #
  galaxy_tags:
    - alpaca
    - operator
    - backup
    - template
    - csv
    - sla
    - monitoring

dependencies: [] 