---
# Generate Variables File

- name: Generate variables file
  ansible.builtin.template:
    src: "{{ template_config.template_dir }}/{{ template_config.variables_template }}"
    dest: "{{ output_config.output_dir }}/{{ output_config.variables_file }}"
    mode: '0644'

- name: Display variables file generation result
  ansible.builtin.debug:
    msg: |
      Variables File Generation:
      - File: {{ output_config.variables_file }}
      - Location: {{ output_config.output_dir }}
      - Contains: ALPACA API config, CSV summary, command summary 