---
# Generate Inventory File

- name: Generate ALPACA API inventory file
  ansible.builtin.template:
    src: "{{ template_config.template_dir }}/{{ template_config.inventory_template }}"
    dest: "{{ output_config.output_dir }}/{{ output_config.inventory_file }}"
    mode: '0644'

- name: Display inventory file generation result
  ansible.builtin.debug:
    msg: |
      Inventory File Generation:
      - File: {{ output_config.inventory_file }}
      - Location: {{ output_config.output_dir }}
      - ALPACA API Host: {{ alpaca_api.host }} 