---
# Dynamic Command Generator Role - Main Tasks

- name: Validate CSV processor configuration
  ansible.builtin.assert:
    that:
      - csv_processor.input_file is defined
      - csv_processor.delimiter is defined
      - output_config.output_dir is defined
    fail_msg: "Required configuration variables are missing"
    success_msg: "CSV processor configuration is valid"

- name: Validate ALPACA API configuration
  ansible.builtin.assert:
    that:
      - ALPACA_Operator_API_Username is defined
      - ALPACA_Operator_API_Password is defined
    fail_msg: "Required ALPACA API variables are missing. Please set ALPACA_Operator_API_Username and ALPACA_Operator_API_Password"
    success_msg: "ALPACA API configuration is valid"

- name: Build ALPACA API configuration
  ansible.builtin.set_fact:
    alpaca_api:
      host: "{{ inventory_hostname }}"
      protocol: "{{ ALPACA_Operator_API_Protocol | default('https') }}"
      port: "{{ ALPACA_Operator_API_Port | default(8443) }}"
      username: "{{ ALPACA_Operator_API_Username }}"
      password: "{{ ALPACA_Operator_API_Password }}"
      tls_verify: "{{ ALPACA_Operator_API_Validate_Certs | default(false) }}"

- name: Check if CSV file exists
  ansible.builtin.stat:
    path: "{{ csv_processor.input_file }}"
  register: csv_file_stat

- name: Fail if CSV file does not exist
  ansible.builtin.fail:
    msg: "CSV file not found: {{ csv_processor.input_file }}"
  when: not csv_file_stat.stat.exists

- name: Display processing information
  ansible.builtin.debug:
    msg: |
      Starting CSV processing for SLA-based ALPACA command generation
      CSV File: {{ csv_processor.input_file }}
      Output Directory: {{ output_config.output_dir }}
      Template Directory: {{ template_config.template_dir }}
      ALPACA API Host: {{ alpaca_api.host }}

- name: Read and process CSV data
  include_tasks: process_csv.yml

- name: Validate CSV data
  include_tasks: validate_csv.yml
  when: processing_options.validate_data | default(true)

- name: Create output directory
  ansible.builtin.file:
    path: "{{ output_config.output_dir }}"
    state: directory
    mode: '0755'

- name: Generate individual command files
  include_tasks: generate_individual_commands.yml
  when: processing_options.generate_individual_files | default(true)

- name: Generate consolidated command file
  include_tasks: generate_consolidated_file.yml
  when: processing_options.generate_consolidated_file | default(true)

- name: Generate inventory file
  include_tasks: generate_inventory.yml
  when: processing_options.generate_inventory | default(true)

- name: Generate variables file
  include_tasks: generate_variables.yml
  when: processing_options.generate_variables | default(true)

- name: Generate README file
  include_tasks: generate_readme.yml
  when: processing_options.generate_readme | default(true)

- name: Display generation summary
  ansible.builtin.debug:
    msg: |
      Dynamic Command Generation Summary:
      - Total rows processed: {{ csv_data | length }}
      - SLA1 systems: {{ csv_data | selectattr('system_sla', 'equalto', 'SLA1') | list | length }}
      - SLA2 systems: {{ csv_data | selectattr('system_sla', 'equalto', 'SLA2') | list | length }}
      - SLA3 systems: {{ csv_data | selectattr('system_sla', 'equalto', 'SLA3') | list | length }}
      - SLA4 systems: {{ csv_data | selectattr('system_sla', 'equalto', 'SLA4') | list | length }}
      - Total commands generated: {{ total_commands_generated | default(0) }}
      - Individual files generated: {{ individual_files_generated | default(0) }}
      - Consolidated file generated: {{ consolidated_file_generated | default(false) }}
      - Output directory: {{ output_config.output_dir }}
  when: csv_data is defined 