---
# Validate CSV Data for Dynamic Command Generation

- name: Validate CSV data structure
  ansible.builtin.assert:
    that:
      - csv_data is defined
      - csv_data | length > 0
    fail_msg: "CSV data is empty or not properly parsed"
    success_msg: "CSV data structure is valid"

- name: Validate required CSV columns
  ansible.builtin.assert:
    that:
      - csv_row.hdb_nw_sid is defined and csv_row.hdb_nw_sid | length > 0
      - csv_row.system_vdns is defined and csv_row.system_vdns | length > 0
      - csv_row.system_sla is defined and csv_row.system_sla | length > 0
      - csv_row.system_type is defined and csv_row.system_type | length > 0
    fail_msg: "Required CSV columns are missing or empty in row {{ loop.index }}: {{ csv_row }}"
    success_msg: "Required CSV columns are present in row {{ loop.index }}"
  loop: "{{ csv_data }}"
  loop_control:
    loop_var: csv_row

- name: Validate SLA values
  ansible.builtin.assert:
    that:
      - csv_row.system_sla in ['SLA1', 'SLA2', 'SLA3', 'SLA4']
    fail_msg: "Invalid SLA value '{{ csv_row.system_sla }}' in row {{ loop.index }}. Must be one of: SLA1, SLA2, SLA3, SLA4"
    success_msg: "SLA value '{{ csv_row.system_sla }}' is valid in row {{ loop.index }}"
  loop: "{{ csv_data }}"
  loop_control:
    loop_var: csv_row

- name: Validate SLA command configuration exists
  ansible.builtin.assert:
    that:
      - csv_row.system_sla in sla_commands
      - sla_commands[csv_row.system_sla].commands is defined
      - sla_commands[csv_row.system_sla].commands | length > 0
    fail_msg: "No command configuration found for SLA '{{ csv_row.system_sla }}' in row {{ loop.index }}"
    success_msg: "Command configuration found for SLA '{{ csv_row.system_sla }}' in row {{ loop.index }}"
  loop: "{{ csv_data }}"
  loop_control:
    loop_var: csv_row

- name: Display validation summary
  ansible.builtin.debug:
    msg: |
      CSV Validation Summary:
      - Total rows validated: {{ csv_data | length }}
      - All required columns present: ✓
      - All SLA values valid: ✓
      - All SLA configurations found: ✓
      - Validation completed successfully 