- name: Configure ALPACA Operator command for MHP
  hosts: local
  gather_facts: false

  tasks:
    - name: "Ensure command BKP: DB shared sync MHP is configured"
      pcg.alpaca_operator.alpaca_command:
        system:
          systemName: "MHP"
          
        command:
          state: present
          name: "BKP: DB shared sync MHP"
          agentName: "hdbmhpa"
          
          parameters: "-p GLTshared -s <BKP_SHARED_SRC> -l 4 -d <BKP_SHARED_DEST1> -r <BKP_SHARED_DEST2> -b <BKP_SHARED_CLEANUP_INT> -t <BKP_SHARED_CLEANUP_INT2> -h DB_HOST"

          schedule:
            period: "every_30min"
            time: "12:00:00"
            cronExpression: ""
            daysOfWeek:
              - monday
              - tuesday
              - wednesday
              - thursday
              - friday
              - saturday
              - sunday
              
          parametersNeeded: False
          disabled: False
          critical: True
          autoDeploy: False
          history:
            documentAllRuns: True
            retention: 100
          timeout:
            type: default
            value: 13
          escalation:
            mailEnabled: True
            smsEnabled: False
            mailAddress: "monitoring@pcg.io"
            smsAddress: ""
            minFailureCount: 1
            triggers:
              everyChange: True
              toRed: True
              toYellow: False
              toGreen: False
        apiConnection:
          host: "nightly03.lnwsoft.corp"
          protocol: "https"
          port: "8443"
          username: "pms*"
          password: "pms"
          tls_verify: "False"