---
- name: Check if csv_file is set
  fail:
    msg: "Variable 'csv_file' is not set. Please set this in the playbook."
  when: csv_file is not defined or csv_file == ""

- name: Check if CSV file exists
  stat:
    path: "{{ csv_file }}"
  register: csv_file_stat

- name: Error if CSV file not found
  fail:
    msg: "CSV file '{{ csv_file }}' was not found."
  when: not csv_file_stat.stat.exists

- name: Read CSV file with Python
  command: python3 "{{ role_path }}/files/read_csv.py" "{{ csv_file }}"
  register: csv_output
  delegate_to: localhost
  changed_when: false

- name: Parse CSV data
  set_fact:
    csv_data: "{{ csv_output.stdout | from_json }}"

# - name: Debug - Show CSV data
#   debug:
#     msg: "Found {{ csv_data | length }} rows in CSV file"
#   when: csv_data is defined

# - name: Debug - Show role defaults
#   debug:
#     msg: "role_defaults: {{ role_defaults }}"

# - name: Debug - Show override
#   debug:
#     msg: "override: {{ override | default('NOT DEFINED') }}"

# - name: Debug - Show JSON strings
#   debug:
#     msg: "Base JSON: {{ role_defaults | to_json }}"
#   when: role_defaults is defined

# - name: Debug - Show override JSON
#   debug:
#     msg: "Override JSON: {{ (override | default({})) | to_json }}"
#   when: override is defined

- name: Merge dictionaries using Python recursive merge
  command: >
    python3 "{{ role_path }}/files/merge_definitions.py"
    '{{ role_defaults | to_json }}'
    '{{ (override | default({})) | to_json }}'
  register: merge_output
  changed_when: false
  when: role_defaults is defined

# - name: Debug - Show merge output
#   debug:
#     msg: "Merge stdout: {{ merge_output.stdout }}"
#     verbosity: 2
#   when: merge_output is defined

# - name: Debug - Show merge stderr
#   debug:
#     msg: "Merge stderr: {{ merge_output.stderr }}"
#     verbosity: 2
#   when: merge_output is defined

- name: Parse merged definitions
  set_fact:
    merged_definitions: "{{ merge_output.stdout | from_json }}"
  when: merge_output is defined and merge_output.stdout != ""

# - name: Debug - Show merged definitions
#   debug:
#     msg: "Merged definitions: {{ merged_definitions }}"
#   when: merged_definitions is defined

- name: Iterate over all CSV rows and generate commands
  include_tasks: process_csv_row.yml
  loop: "{{ csv_data }}"
  loop_control:
    loop_var: csv_row
    index_var: row_index
  when: csv_data is defined
