---

- name: Set variables for current CSV row
  set_fact:
    csv:
      systemName: "{{ csv_row.hdb_nw_sid | default(omit) }}"
      agentName: "{{ csv_row.system_vdns | default(omit) }}"
      systemSla: "{{ csv_row.system_sla | default(omit) }}"
      systemType: "{{ csv_row.system_type | default(omit) }}"
      systemStaging: "{{ csv_row.system_staging | default(omit) }}"
      instanceNo: "{{ csv_row.Instance_no | default(omit) }}"

# - name: Debug - Show current row
#   debug:
#     msg: |
#       Processing row {{ row_index }}:
#       - System: {{ csv.systemName }}
#       - Agent: {{ csv.agentName }}
#       - SLA: {{ csv.systemSla }}
#       - Type: {{ csv.systemType }}

# - name: Debug - Show command count
#   debug:
#     msg: "{{ csv.systemSla }} gets {{ command_templates[csv.systemSla] | length }} commands"

- name: Generate commands for current row
  include_tasks: generate_commands.yml
  loop: "{{ command_templates[csv.systemSla] }}"
  loop_control:
    loop_var: command_template
    index_var: command_index