---
- name: Set variables for current CSV row
  set_fact:
    csv:
      systemName: "{{ csv_row.hdb_nw_sid | default(omit) }}"
      agentName: "{{ csv_row.system_vdns | default(omit) }}"
      systemSla: "{{ csv_row.system_sla | default(omit) }}"
      systemType: "{{ csv_row.system_type | default(omit) }}"
      systemStaging: "{{ csv_row.system_staging | default(omit) }}"
      instanceNo: "{{ csv_row.Instance_no | default(omit) }}"

- name: Set SLA and default command sets for current CSV row
  set_fact:
    sla_command_set: "{{ merged_definitions.service_levels[csv.systemSla].commands | default([]) }}"
    default_command_set: "{{ merged_definitions.commands | default([]) }}"

- name: "Debug: Show sla_command_set (readable)"
  debug:
    var: sla_command_set | default([])
    verbosity: 1

- name: "Debug: Show default_command_set (readable)"
  debug:
    var: default_command_set | default([])
    verbosity: 1

- name: "[merge:sla-commands->default-commands] Merge SLA specific commands into default command set"
  set_fact:
    merged_command_set: "{{ (default_command_set | default([])) + (sla_command_set | default([])) }}"

- name: "Debug: Show merged_command_set (readable)"
  debug:
    var: merged_command_set
    verbosity: 1

- name: "Debug: Show command count for current csv row / SLA"
  debug:
    msg: "{{ csv.systemSla }} gets {{ merged_command_set | length }} commands"

- name: Generate commands for current csv row
  include_tasks: process_command.yml
  loop: "{{ merged_command_set }}"
  loop_control:
    loop_var: command_definition
    index_var: command_index