---

- name: Set variables for current CSV row
  set_fact:
    csv:
      systemName: "{{ csv_row.hdb_nw_sid | default(omit) }}"
      agentName: "{{ csv_row.system_vdns | default(omit) }}"
      systemSla: "{{ csv_row.system_sla | default(omit) }}"
      systemType: "{{ csv_row.system_type | default(omit) }}"
      systemStaging: "{{ csv_row.system_staging | default(omit) }}"
      instanceNo: "{{ csv_row.Instance_no | default(omit) }}"

- name: Set definitions for current CSV row
  set_fact:
    definitions:
      global_defaults: "{{ merged_definitions.global_defaults | default(omit) }}"
      sla_defaults: "{{ merged_definitions.service_levels[csv.systemSla].defaults | default(omit) }}"

# - name: Debug - Show current row
#   debug:
#     msg: |
#       Processing row {{ row_index }}:
#       - System: {{ csv.systemName }}
#       - Agent: {{ csv.agentName }}
#       - SLA: {{ csv.systemSla }}
#       - Type: {{ csv.systemType }}

# - name: Debug - Show command count
#   debug:
#     msg: "{{ csv.systemSla }} gets {{ merged_definitions.service_levels[csv.systemSla].commands | length }} commands"

# - name: Debug - Show definitions
#   debug:
#     msg: |
#       global_defaults: {{ definitions.global_defaults }}
#       sla_defaults: {{ definitions.sla_defaults }}

- name: Generate commands for current row
  include_tasks: generate_commands.yml
  loop: "{{ merged_definitions.service_levels[csv.systemSla].commands }}"
  loop_control:
    loop_var: command_definition
    index_var: command_index